### ISSUE TITLE
Lens distortion

### ISSUE THREAD

**Issue by mpalmsten** [Coastal-Imaging-Research-Network/Forum-Wiki#8]
Run the CalTech toolbox using the example provided by @RobHolman in this repository

**Comment by SRHarrison** [comment]
I followed along through the description of Lens Distortion. 

The Caltech toolbox (also my fav.) worked well with the demo images provided. I was able to get similar results as presented in the wiki. However, I think that (we) should include the pixel error values. Everyone will get slightly different results, so it would be helpful to compare pixel error values to assess whether their calibration is better or worse - and if extra calibration steps are required.


Other feedback on the Lenses page: 
- the linked/embedded images in the wiki Lens page are too large (10 and 20MB) and make the browser feel heavy. I will resize these and update.
- the equations don't display because tiff images are not supported by html. I will convert them to png and repost.
